### ISSUE TITLE
Data not adding up

### ISSUE THREAD

**Issue by s4nyam** [GAUTAMRAJU15/electron-shopping-demoapp#1]
Bro I am adding data to add window and the results are not showing in index.

**Comment by 0xAnon101** [comment]
Do ```npm install``` and make sure electron is installed on your system

**Comment by s4nyam** [comment]
Okay my dear Raju!

**Comment by 0xAnon101** [comment]
@samy280497 did it worked , because it's working on my system.

**Comment by s4nyam** [comment]
haan bro, I ll check once I get time.
Thanks for the support, I forgot to install node modules

>

**Comment by 0xAnon101** [comment]
@samy280497 sure
